### ISSUE TITLE
Get all entries - archive should not be set

### ISSUE THREAD

**Issue by ngosang** [push-things/wallabag_api#8]
Your current implementation don't work like I was expecting.

Wallabag API:
* get_entries without "archive" parameter =>  all articles
* get_entries with "archive" = 0 => not archived
* get_entries with "archive" = 1 => archived

Your implementation:
* get_entries without "archive" parameter =>  you send "archive" = 0 => not archive
* get_entries with "archive" = 0 => not archived
* get_entries with "archive" = 1 => archived

There is no way to get all articles in your current implementation...

**Comment by foxmask** [comment]
true
I'll check if archive is in the kwargs in `get_entries`  https://github.com/push-things/wallabag_api/blob/master/wallabag_api/wallabag.py#L132 , if no, params will not have archive too https://github.com/push-things/wallabag_api/blob/master/wallabag_api/wallabag.py#L153 and wont pass that parm to the query call .https://github.com/push-things/wallabag_api/blob/master/wallabag_api/wallabag.py#L191
